package com.db.logic;

import com.db.sql.SQLType;
import com.db.util.Constants;
import org.apache.log4j.Logger;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

/**
 * 逻辑库的PreparedStatement类
 * @date 2014年6月23日 上午9:58:18 
 * @version V1.0
 */
public class LogicDBPreparedStatement  extends LogicDBStatement implements PreparedStatement {
	public static final Logger log = Logger.getLogger(LogicDBPreparedStatement.class);
	
	private Map<Integer, Integer> typeMap = new HashMap<Integer,Integer>();
	private Map<Integer,Object> valueMap = new HashMap<Integer,Object>();
	private String sql;
	private int autoGeneratedKeys = -1;
	private int[] columnIndexes;
	private String[] columnNames;

	public LogicDBPreparedStatement(String sql) {
		super();
		this.setSql(sql);
		dbStmtList = new ArrayList<>();
	}
	
	@Override
	public boolean execute() throws SQLException {
		if(this.isClosed()) {
			return false;
		}
		String sqlType = SQLType.getSqlType(sql);
		if(SQLType.SELECT.equals(sqlType)) {
			this.setResultSet(executeQuery());
			return true;
		}else{
			this.updateCount = executeUpdate();
			return true;
		}
	}

	@Override
	public void addBatch() throws SQLException {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public int[] executeBatch() throws SQLException {
		// TODO Auto-generated method stub
		return super.executeBatch();
	}

	public ResultSet executeQuery(int flag) throws SQLException {
		if(this.isClosed()) {
			return null;
		}
		this.processDbRule(sql);

		Connection conn = getRealConnection(getDbName());
		PreparedStatement ps = null;
		if (this.autoGeneratedKeys != -1) {
			ps = conn.prepareStatement(getSql(), this.autoGeneratedKeys);
		} else if (this.columnIndexes != null && this.columnIndexes.length > 0) {
			ps = conn.prepareStatement(getSql(), this.columnIndexes);
		} else if (this.columnNames != null && this.columnNames.length > 0) {
			ps = conn.prepareStatement(getSql(), this.columnNames);
		} else if (this.getResultSetType() != -1 && this.getResultSetConcurrency() != -1 && this.getResultSetHoldability() != -1) {
			ps = conn.prepareStatement(getSql(), this.getResultSetType(), this.getResultSetConcurrency(), this.getResultSetHoldability());
		} else if (this.getResultSetType() != -1 && this.getResultSetConcurrency() != -1) {
			ps = conn.prepareStatement(getSql(), this.getResultSetType(), this.getResultSetConcurrency());
		} else {
			ps = conn.prepareStatement(getSql());
		}
		manager.addStatement(ps);
		if (flag == Constants.NORMAL_DB_FLAG) {
			dbStmtList.add(ps);
		}
		for (Integer key : this.valueMap.keySet()) {
			ps.setObject(key, this.valueMap.get(key));
		}
		long beginTime = System.currentTimeMillis();
		super.realSmt=ps;//jys
		ResultSet rs = ps.executeQuery();
		long endTime = System.currentTimeMillis();
		if (log.isDebugEnabled()) {
			log.debug("dbName(" + getDbName() + ") cost " + (endTime - beginTime) + " ms to execute sql: " + getSql());
			log.debug(this.valueMap);
		}
		return rs;
	}

	@Override
	public ResultSet executeQuery() throws SQLException {
		return executeQuery(Constants.NORMAL_DB_FLAG);
	}

//	@Override
//	public void close() throws SQLException {
//		for (Statement stmt : dbStmtList) {
//			stmt.close();
//		}
//		dbStmtList.clear();
//		super.close();
//	}

	@Override
	public int executeUpdate() throws SQLException {
		if(this.isClosed()) {
			return -1;
		}
		this.processDbRule(sql);
		Connection conn = getRealConnection(getDbName());
		PreparedStatement ps = null;
		try {
			if (this.autoGeneratedKeys != -1) {
				ps = conn.prepareStatement(getSql(), this.autoGeneratedKeys);
			} else if (this.columnIndexes != null && this.columnIndexes.length > 0) {
				ps = conn.prepareStatement(getSql(), this.columnIndexes);
			} else if (this.columnNames != null && this.columnNames.length > 0) {
				ps = conn.prepareStatement(getSql(), this.columnNames);
			} else if (this.getResultSetType() != -1 && this.getResultSetConcurrency() != -1 && this.getResultSetHoldability() != -1) {
				ps = conn.prepareStatement(getSql(), this.getResultSetType(), this.getResultSetConcurrency(), this.getResultSetHoldability());
			} else if (this.getResultSetType() != -1 && this.getResultSetConcurrency() != -1) {
				ps = conn.prepareStatement(getSql(), this.getResultSetType(), this.getResultSetConcurrency());
			} else {
				ps = conn.prepareStatement(getSql());
			}
			manager.addStatement(ps);
			for (Integer key : this.valueMap.keySet()) {
				Integer type = this.typeMap.get(key);
				if (type.intValue() == Types.BINARY) {
					@SuppressWarnings("unchecked")
					Map<String, Object> valueMap = (Map<String, Object>) this.valueMap.get(key);
					Object len = valueMap.get("length");
					if (null == len) {
						ps.setBinaryStream(key, (InputStream) valueMap.get("value"));
					} else {
						ps.setBinaryStream(key, (InputStream) valueMap.get("value"), (Long) len);
					}

				} else if (type.intValue() == Types.NCLOB) {
					@SuppressWarnings("unchecked")
					Map<String, Object> valueMap = (Map<String, Object>) this.valueMap.get(key);
					Object len = valueMap.get("length");
					if (null == len) {
						ps.setClob(key, (Reader) valueMap.get("value"));
					} else {
						ps.setClob(key, (Reader) valueMap.get("value"), (Long) len);
					}

				} else {
					ps.setObject(key, this.valueMap.get(key));
				}

//		    ps.setObject(key, this.valueMap.get(key));
			}
			realSmt=ps;//jys
			long beginTime = System.currentTimeMillis();
			int i = ps.executeUpdate();
			long endTime = System.currentTimeMillis();
			if (log.isDebugEnabled()) {
				log.debug("dbName(" + getDbName() + ") cost " + (endTime - beginTime) + " ms to execute sql: " + getSql());
				log.debug(this.valueMap);
				log.debug(i + " records were updated.");
			}
			return i;
		} finally {
			if (null != ps) {
				ps.close();
				if(log.isDebugEnabled()){
					log.debug("===============executeUpdate 游标释放===================");
				}
			}
		}
	}

	@Override
	public void setObject(int parameterIndex, Object x) throws SQLException {
		typeMap.put(parameterIndex, Types.OTHER);
		valueMap.put(parameterIndex, x);
	}
	
	@Override
	public void setRowId(int parameterIndex, RowId x) throws SQLException {
		typeMap.put(parameterIndex, Types.ROWID);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setNString(int parameterIndex, String value)
			throws SQLException {
		typeMap.put(parameterIndex, Types.NVARCHAR);
		valueMap.put(parameterIndex, value);
	}

	@Override
	public void setRef(int parameterIndex, Ref x) throws SQLException {
		typeMap.put(parameterIndex, Types.REF);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setBlob(int parameterIndex, Blob x) throws SQLException {
		typeMap.put(parameterIndex, Types.BLOB);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setClob(int parameterIndex, Clob x) throws SQLException {
		typeMap.put(parameterIndex, Types.CLOB);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setArray(int parameterIndex, Array x) throws SQLException {
		typeMap.put(parameterIndex, Types.ARRAY);
		valueMap.put(parameterIndex, x);
	}
	
	@Override
	public void setNull(int parameterIndex, int sqlType) throws SQLException {
		typeMap.put(parameterIndex, Types.NULL);
		valueMap.put(parameterIndex, null);
	}

	@Override
	public void setBoolean(int parameterIndex, boolean x) throws SQLException {
		typeMap.put(parameterIndex, Types.BOOLEAN);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setByte(int parameterIndex, byte x) throws SQLException {
		typeMap.put(parameterIndex, Types.TINYINT);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setShort(int parameterIndex, short x) throws SQLException {
		typeMap.put(parameterIndex, Types.SMALLINT);
		valueMap.put(parameterIndex, x);
	}

	

	@Override
	public void setTimestamp(int parameterIndex, Timestamp x)
			throws SQLException {
		typeMap.put(parameterIndex, Types.TIMESTAMP);
		valueMap.put(parameterIndex, x);
	}
	
	@Override
	public void setInt(int parameterIndex, int x) throws SQLException {
		typeMap.put(parameterIndex, Types.INTEGER);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setLong(int parameterIndex, long x) throws SQLException {
		typeMap.put(parameterIndex, Types.BIGINT);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setFloat(int parameterIndex, float x) throws SQLException {
		typeMap.put(parameterIndex, Types.FLOAT);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setDouble(int parameterIndex, double x) throws SQLException {
		typeMap.put(parameterIndex, Types.DOUBLE);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setBigDecimal(int parameterIndex, BigDecimal x)
			throws SQLException {
		typeMap.put(parameterIndex, Types.DECIMAL);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setString(int parameterIndex, String x) throws SQLException {
		typeMap.put(parameterIndex, Types.VARCHAR);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setBytes(int parameterIndex, byte[] x) throws SQLException {
		typeMap.put(parameterIndex, Types.CLOB);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setDate(int parameterIndex, Date x) throws SQLException {
		typeMap.put(parameterIndex, Types.DATE);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setTime(int parameterIndex, Time x) throws SQLException {
		typeMap.put(parameterIndex, Types.TIME);
		valueMap.put(parameterIndex, x);
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
	    setBinaryStream(parameterIndex,x,Long.valueOf(length));
	}

	@Override
	public void clearParameters() throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
	    setCharacterStream(parameterIndex,reader,Long.valueOf(length));
	}

	@Override
	public ResultSetMetaData getMetaData() throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setURL(int parameterIndex, URL x) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setNClob(int parameterIndex, NClob value) throws SQLException {
		typeMap.put(parameterIndex, Types.NCHAR);
		valueMap.put(parameterIndex, value);
	}

	@Override
	public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
	    setCharacterStream(parameterIndex,reader,length);
	}

	@Override
	public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
	    setBinaryStream(parameterIndex,inputStream,length);
	}

	@Override
	public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
	    this.typeMap.put(parameterIndex, Types.BINARY);
        Map<String,Object> valueMap=new HashMap<String,Object>();
        valueMap.put("value", x);
        valueMap.put("length", length);
        this.valueMap.put(parameterIndex, valueMap);
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
	    this.typeMap.put(parameterIndex, Types.NCLOB);
        Map<String,Object> valueMap=new HashMap<String,Object>();
        valueMap.put("value", reader);
        valueMap.put("length", length);
        this.valueMap.put(parameterIndex, valueMap);
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
	    this.typeMap.put(parameterIndex, Types.BINARY);
        Map<String,Object> valueMap=new HashMap<String,Object>();
        valueMap.put("value", x);
        this.valueMap.put(parameterIndex, valueMap);
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
	    this.typeMap.put(parameterIndex, Types.NCLOB);
        Map<String,Object> valueMap=new HashMap<String,Object>();
        valueMap.put("value", reader);
        this.valueMap.put(parameterIndex, valueMap);
	}

	@Override
	public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
		throw new SQLException("unsupported operation");
	}

	@Override
	public void setClob(int parameterIndex, Reader reader) throws SQLException {
	    setCharacterStream(parameterIndex,reader);
	}

	@Override
	public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
	    setBinaryStream(parameterIndex,inputStream);
	}

	@Override
	public void setNClob(int parameterIndex, Reader reader) throws SQLException {
		throw new SQLException("unsupported operation");
	}
	
	protected String getSql() {
		return sql;
	}

	protected void setSql(String sql) {
		this.sql = sql;
	}

	public int getAutoGeneratedKeys() {
		return autoGeneratedKeys;
	}

	public void setAutoGeneratedKeys(int autoGeneratedKeys) {
		this.autoGeneratedKeys = autoGeneratedKeys;
	}

	public int[] getColumnIndexes() {
		return columnIndexes;
	}

	public void setColumnIndexes(int[] columnIndexes) {
		this.columnIndexes = columnIndexes;
	}

	public String[] getColumnNames() {
		return columnNames;
	}

	public void setColumnNames(String[] columnNames) {
		this.columnNames = columnNames;
	}
}
